### ISSUE TITLE
Fails to build in an app - bower/ ... /tether.js missing

### ISSUE THREAD

**Issue by BryanCrotaz** [yapplabs/ember-tether#21]
Fails on both Windows and Mac:
```
ENOENT: no such file or directory, stat 'G:\Projects\sc-ds-prototype\tmp\concat_with_maps-input_base_path-2IxSvwqv.tmp\0\bower_components\tether\dist\js\tether.
js'
Error: ENOENT: no such file or directory, stat 'G:\Projects\sc-ds-prototype\tmp\concat_with_maps-input_base_path-2IxSvwqv.tmp\0\bower_components\tether\dist\js\
tether.js'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at ConcatWithMaps.keyForFile (G:\Projects\sc-ds-prototype\node_modules\ember-cli\node_modules\broccoli-sourcemap-concat\node_modules\broccoli-caching-writer
\index.js:91:55)
    at Array.map (native)
    at ConcatWithMaps.CachingWriter._conditionalBuild (G:\Projects\sc-ds-prototype\node_modules\ember-cli\node_modules\broccoli-sourcemap-concat\node_modules\br
occoli-caching-writer\index.js:107:61)
    at G:\Projects\sc-ds-prototype\node_modules\ember-cli\node_modules\broccoli-sourcemap-concat\node_modules\broccoli-caching-writer\node_modules\broccoli-plug
in\read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (G:\Projects\sc-ds-prototype\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (G:\Projects\sc-ds-prototype\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (G:\Projects\sc-ds-prototype\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:476:11)
    at lib$rsvp$asap$$flush (G:\Projects\sc-ds-prototype\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
```

**Comment by BryanCrotaz** [comment]
The whole `bower_components\tether folder` is missing.

Installed with

`npm install --save ember-tether`

**Comment by chrislopresto** [comment]
@BryanCrotaz Running `ember install ember-tether` should do this all for you automatically.

The 'magic' is in the blueprint here: https://github.com/yapplabs/ember-tether/blob/2995ddd119a0d7564796b078a8e981df39078ce1/blueprints/ember-tether/index.js

Closing this. Please comment or reopen if this doesn't do the trick for you.

**Comment by BryanCrotaz** [comment]
Ah. Then the problem is the readme doesn't say how to install it.

**Comment by chrislopresto** [comment]
Good point. Any interest in submitting a PR with a section explaining?

The section in the ember-modal-dialog README looks like this: 
https://github.com/yapplabs/ember-modal-dialog#including-in-an-ember-application

**Comment by BryanCrotaz** [comment]
Yes, but up against a tight deadline this week :(
