### ISSUE TITLE
Latest release doesn't match package.json

### ISSUE THREAD

**Issue by HeroicEric** [yapplabs/ember-tether#28]
Latest release on the releases page is 0.3.0 but package.json still says 0.2.1.

This is weird because there is a commit included with the release that bumps package.json https://github.com/yapplabs/ember-tether/commit/47b47b14d92eed3439c9b2c2f15347c19e0a133d

Trying to use 0.2.1 gives the following error, but is fixed with 0.3.0 and removing tether.js from bower.json:

```
$ ember server
version: 2.4.2
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, stat '/Users/eric/code/rbm/cpc/tmp/source_map_concat-input_base_path-SVjclbGs.tmp/0/bower_components/tether/dist/js/tether.js'
    at Error (native)
    at Object.fs.statSync (fs.js:849:18)
    at ConcatWithMaps.keyForFile (/Users/eric/code/rbm/cpc/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/index.js:90:20)
    at Array.map (native)
    at ConcatWithMaps.CachingWriter._conditionalBuild (/Users/eric/code/rbm/cpc/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/index.js:112:65)
    at /Users/eric/code/rbm/cpc/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/Users/eric/code/rbm/cpc/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/eric/code/rbm/cpc/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/eric/code/rbm/cpc/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/eric/code/rbm/cpc/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)

The broccoli plugin was instantiated at:
    at ConcatWithMaps.Plugin (/Users/eric/code/rbm/cpc/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at ConcatWithMaps.CachingWriter [as constructor] (/Users/eric/code/rbm/cpc/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/index.js:21:10)
    at new ConcatWithMaps (/Users/eric/code/rbm/cpc/node_modules/ember-cli/node_modules/broccoli-concat/concat.js:22:17)
    at module.exports (/Users/eric/code/rbm/cpc/node_modules/ember-cli/node_modules/broccoli-concat/index.js:26:10)
    at EmberApp.concatFiles (/Users/eric/code/rbm/cpc/node_modules/ember-cli/lib/broccoli/ember-app.js:329:10)
    at EmberApp.javascript (/Users/eric/code/rbm/cpc/node_modules/ember-cli/lib/broccoli/ember-app.js:1190:12)
    at EmberApp.toArray (/Users/eric/code/rbm/cpc/node_modules/ember-cli/lib/broccoli/ember-app.js:1542:10)
    at EmberApp.toTree (/Users/eric/code/rbm/cpc/node_modules/ember-cli/lib/broccoli/ember-app.js:1564:30)
    at module.exports (/Users/eric/code/rbm/cpc/ember-cli-build.js:44:14)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/eric/code/rbm/cpc/node_modules/ember-cli/lib/models/builder.js:55:19)
```

**Comment by chrislopresto** [comment]
Whoops. Good eye. Should be fixed now.
